dynamixel_pan_tilt:
  device_name: /dev/ttyUSB0
  dxl_baudrate: 1000000
  dxl_protocol_version: 2.0
  servo_common:
    position_home: 2048
    position_max: 3300
    position_min: 796
    goal_tolerance: 2
    moving_velocity: 0
    acceleration_profile: 10 # protocol 2.0 only
    address:
      operating_mode: 11 # protocol 2.0 only
      torque_enable: 64
      goal_position: 116
      present_position: 132
      goal_velocity: 104 # protocol 2.0 only
      profile_velocity: 112 # protocol 2.0 only
      profile_acceleration: 108 # protocol 2.0 only
      moving_velocity: 32 # protocol 1.0 only
      cw_angle_limit: 6 # protocol 1.0 only
      ccw_angle_limit: 8 # protocol 1.0 only
    address_value:
      operating_mode_velocity_control: 1 # protocol 2.0 only
      operating_mode_position_control: 3 # protocol 2.0 only
  pan_servo:
    id: 0
  tilt_servo:
    id: 1